include_guard(GLOBAL)

# Include only public API commands.
include(cupcake_project)
include(cupcake_find_package)
include(cupcake_find_packages)
include(cupcake_add_subproject)
include(cupcake_add_library)
include(cupcake_add_libraries)
include(cupcake_add_executable)
include(cupcake_add_executables)
include(cupcake_add_test)
include(cupcake_add_tests)
include(cupcake_enable_testing)
include(cupcake_link_libraries)
include(cupcake_install_project)
include(cupcake_install_cpp_info)
